# Generated by Django 5.2 on 2025-04-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="photos", to="tags.tag"),
        ),
    ]
